#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=1

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Finding an available port..." --weight=1

# Find an available port.
# It will be used to run a specific yunohost-api Server (see ../conf/systemd.service file)
port=$(ynh_find_port --port=6788)
ynh_app_setting_set --app=$app --key=port --value=$port

#=================================================
# DOWNLOAD, CHECK, UNPACK and PATCH SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=11

ynh_app_setting_set --app=$app --key=final_path --value=$final_path

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$final_path"

for file in `find $final_path -type f`
do
    ynh_replace_string --match_string="/ynh-users-groups" --replace_string="${path_url%/}" --target_file=$file
done


#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
#=================================================
# ADD ADMIN GROUP AND PERMISSIONS
#=================================================
ynh_script_progression --message="Configuring the admin group and permissions..." --weight=1

if ! ynh_exec_fully_quiet "yunohost user group info admin"
then
    yunohost user group create admin
fi

ynh_permission_update --permission=main --remove=all_users --add=admin

#=================================================
# MOULINETTE CONFIGURATION
#=================================================
ynh_script_progression --message="Copying the Moulinette actionsmap file..." --weight=1
mkdir -p /etc/$app/actionsmap
ynh_add_config --template="yunohost.yml" --destination="/etc/$app/actionsmap/yunohost.yml"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression  --message="Configuring a systemd service..." --weight=1
ynh_add_systemd_config  --service=$app-api --others_var='port'

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
chown -R root: $final_path

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1
yunohost service add $app-api --description="Permet les interactions entre l'application Yunohost Users-Groups et le système"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1
ynh_systemd_action --service_name=$app-api --action=restart

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
